- hosts: hp_disk
  become: yes
  gather_facts: no

  tasks:
    - name: upload hpssacli
      copy:
        src: files/hpssacli-2.40-13.0.x86_64.rpm
        dest: /tmp/hpssacli-2.40-13.0.x86_64.rpm

    - name: install hpssacli rpm from a local file
      yum:
        name: /tmp/hpssacli-2.40-13.0.x86_64.rpm
        #state: present
        state: installed

    - name: Check Disk Status
      command: hpssacli ctrl all show config
      register: result

    - name: Log check info/hpssacli ctrl all show config
      lineinfile:
        dest: "{{inventory_dir}}/hp_disk_check.log"
        line: '{{inventory_hostname}}'
        insertafter: EOF
        create: yes
      when: ("Failure" in result.stdout)
      delegate_to: localhost
      become: no

    - name: Log check info/hpssacli ctrl all show config
      lineinfile:
        dest: "{{inventory_dir}}/hp_disk_check.log"
        line: '{{inventory_hostname}}'
        insertafter: EOF
        create: yes
      when: ("Failed" in result.stdout)
      delegate_to: localhost
      become: no
